/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_connectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_credentials"];
        put?: never;
        post: operations["post_api_credentials"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_credentials_id"];
        put?: never;
        post?: never;
        delete: operations["delete_api_credentials_id"];
        options?: never;
        head?: never;
        patch: operations["patch_api_credentials_id"];
        trace?: never;
    };
    "/api/credentials/{id}/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_credentials_id_browse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{id}/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_credentials_id_oauth_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_credentials_id_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{id}/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_credentials_id_strategies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_credentials_id_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credentials/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_credentials_id_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_oauth_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_runs_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_api_settings"];
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_tasks"];
        put?: never;
        post: operations["post_api_tasks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/validate-cron": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_tasks_validate_cron"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_tasks_id"];
        put?: never;
        post?: never;
        delete: operations["delete_api_tasks_id"];
        options?: never;
        head?: never;
        patch: operations["patch_api_tasks_id"];
        trace?: never;
    };
    "/api/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_tasks_id_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_api_tasks_id_documents"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_tasks_id_dry_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/full-reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_tasks_id_full_reconcile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/full-reingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_tasks_id_full_reingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_tasks_id_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_tasks_id_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Breadcrumb: {
            id: string;
            name: string;
        };
        BrowseItem: {
            hasChildren: boolean;
            id: string;
            kind: string;
            name: string;
            path: string;
            selectable: boolean;
        };
        BrowseResult: {
            breadcrumbs: components["schemas"]["Breadcrumb"][];
            items: components["schemas"]["BrowseItem"][];
            parentId: string;
        };
        Capabilities: {
            deletionMode: string;
            incrementalMode: string;
            supportsAdvancedFilter: boolean;
            supportsFiles: boolean;
            supportsInlineMultimodal: boolean;
            supportsOAuth: boolean;
        };
        Config: {
            address: string;
            password: string;
            /** @enum {string} */
            type: "default" | "none" | "http" | "https" | "socks5";
            username: string;
        };
        CredentialType: {
            description: string;
            fields: components["schemas"]["FieldSpec"][];
            name: string;
            oauth: boolean;
            type: string;
        };
        DryRunItem: {
            action: string;
            name: string;
            path: string;
            reason: string;
            sourceItemId: string;
            warnings?: string[];
        };
        DryRunResult: {
            complete: boolean;
            createdCount: number;
            deletedCount: number;
            discoveredCount: number;
            error: string;
            failedCount: number;
            items: components["schemas"]["DryRunItem"][];
            skippedCount: number;
            truncated: boolean;
            unchangedCount: number;
            updatedCount: number;
        };
        FieldSpec: {
            browse?: boolean;
            browseKind?: string;
            default?: unknown;
            help?: string;
            key: string;
            label: string;
            options?: components["schemas"]["Option"][];
            placeholder?: string;
            required: boolean;
            secret: boolean;
            /** @enum {string} */
            type: "string" | "password" | "number" | "boolean" | "select" | "url" | "textarea";
        };
        FilePolicy: {
            audios: boolean;
            documents: boolean;
            images: boolean;
            plainText: boolean;
        };
        Filter: {
            advancedQuery: string;
            /** @enum {string} */
            mode: "simple" | "advanced";
            rules: components["schemas"]["FilterRule"][];
        };
        FilterFieldSpec: {
            key: string;
            label: string;
            operators: ("equals" | "notEquals" | "contains" | "in" | "notIn" | "greaterThan" | "lessThan")[];
            options?: components["schemas"]["Option"][];
            /** @enum {string} */
            type: "string" | "boolean" | "number" | "datetime" | "enum";
        };
        FilterRule: {
            field: string;
            /** @enum {string} */
            operator: "equals" | "notEquals" | "contains" | "in" | "notIn" | "greaterThan" | "lessThan";
            value: unknown;
        };
        Option: {
            label: string;
            value: string;
        };
        Scope: {
            /** @enum {string} */
            rule: "combined" | "shared" | "per_tag" | "all_combinations" | "custom";
            scopes: components["schemas"]["TagRef"][][];
        };
        SourceInfo: {
            browseKinds: string[];
            capabilities: components["schemas"]["Capabilities"];
            credentialType: string;
            fields: components["schemas"]["FieldSpec"][];
            filterFields: components["schemas"]["FilterFieldSpec"][];
            name: string;
            type: string;
        };
        Tag: {
            count: number;
            tag: string;
        };
        TagPage: {
            items: components["schemas"]["Tag"][];
            limit: number;
            offset: number;
            total: number;
        };
        TagRef: {
            /** @enum {string} */
            kind: "literal" | "dynamic";
            value: string;
        };
        apiError: {
            code: string;
            error: string;
            fields?: {
                [key: string]: string;
            };
        };
        cancelDTO: {
            cancelled: boolean;
        };
        connectorsDTO: {
            credentialTypes: components["schemas"]["CredentialType"][];
            sources: components["schemas"]["SourceInfo"][];
        };
        credRef: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "active" | "reauth_required" | "pending_oauth" | "error";
            type: string;
        };
        credentialDTO: {
            config: {
                [key: string]: unknown;
            };
            createdAt: string;
            customHeaders: {
                [key: string]: string;
            };
            id: string;
            name: string;
            oauthConnected: boolean;
            oauthExpiresAt: string | null;
            proxy: components["schemas"]["Config"];
            /** @enum {string} */
            proxyMode: "global" | "override";
            /** @enum {string} */
            status: "active" | "reauth_required" | "pending_oauth" | "error";
            statusMessage: string;
            type: string;
            updatedAt: string;
            usedByTasks: number;
        };
        credentialProxyBody: {
            address: string;
            password: string | null;
            /** @enum {string} */
            type: "default" | "none" | "http" | "https" | "socks5";
            username: string;
        };
        cronDTO: {
            error: string;
            nextRuns: string[];
            valid: boolean;
        };
        dashboardDTO: {
            enabledTasks: number;
            nextRuns: components["schemas"]["nextRun"][];
            reauthCredentials: components["schemas"]["credRef"][];
            recentFailures: components["schemas"]["runDTO"][];
            runningTasks: components["schemas"]["running"][];
            totalTasks: number;
            totals: components["schemas"]["dashboardTotals"];
        };
        dashboardTotals: {
            failed24h: number;
            items: number;
            runs24h: number;
        };
        deleteDocumentsDTO: {
            deletedCount: number;
        };
        healthDTO: {
            authEnabled: boolean;
            dbType: string;
            /** @enum {string} */
            status: "active" | "reauth_required" | "pending_oauth" | "error";
            version: string;
        };
        logDTO: {
            level: string;
            message: string;
            time: string;
        };
        nextRun: {
            nextRunAt: string;
            taskId: string;
            taskName: string;
        };
        oauthStartDTO: {
            authUrl: string;
        };
        operationDTO: {
            createdAt: string;
            id: string;
            remoteOperationId: string;
            retryCount: number;
            /** @enum {string} */
            status: "pending" | "running" | "waiting_operations" | "succeeded" | "failed" | "interrupted" | "cancelled";
            type: string;
            updatedAt: string;
        };
        runDTO: {
            createdCount: number;
            deletedCount: number;
            discoveredCount: number;
            errorMessage: string;
            failedCount: number;
            finishedAt: string | null;
            id: string;
            scheduledFor: string | null;
            skippedCount: number;
            startedAt: string | null;
            /** @enum {string} */
            status: "pending" | "running" | "waiting_operations" | "succeeded" | "failed" | "interrupted" | "cancelled";
            syncMode: string;
            taskId: string;
            taskName: string;
            triggerType: string;
            unchangedCount: number;
            updatedCount: number;
        };
        runDetailDTO: {
            createdCount: number;
            cursorAfter: string;
            cursorBefore: string;
            deletedCount: number;
            discoveredCount: number;
            errorMessage: string;
            failedCount: number;
            finishedAt: string | null;
            id: string;
            log: components["schemas"]["logDTO"][];
            operations: components["schemas"]["operationDTO"][];
            scheduledFor: string | null;
            skippedCount: number;
            startedAt: string | null;
            /** @enum {string} */
            status: "pending" | "running" | "waiting_operations" | "succeeded" | "failed" | "interrupted" | "cancelled";
            syncMode: string;
            taskId: string;
            taskName: string;
            triggerType: string;
            unchangedCount: number;
            updatedCount: number;
        };
        runPageDTO: {
            items: components["schemas"]["runDTO"][];
            total: number;
        };
        runTriggeredDTO: {
            runId: string;
        };
        running: {
            runId: string;
            startedAt: string | null;
            /** @enum {string} */
            status: "pending" | "running" | "waiting_operations" | "succeeded" | "failed" | "interrupted" | "cancelled";
            taskId: string;
            taskName: string;
        };
        settingsDTO: {
            filePolicy: components["schemas"]["FilePolicy"];
            fullReconcileIntervalHours: number;
            incrementalSyncEnabled: boolean;
            inlineMultimodalEnabled: boolean;
            maxFileSizeMB: number;
            oauthRedirectUri: string;
            observationScope: components["schemas"]["Scope"];
            proxy: components["schemas"]["Config"];
            timezone: string;
        };
        strategiesDTO: {
            defaultStrategy: string;
            strategies: string[];
        };
        taskDTO: {
            configRevision: number;
            createdAt: string;
            cronExpression: string;
            customMetadata: {
                [key: string]: string;
            };
            customTags: string[];
            destinationBankId: string;
            destinationCredentialId: string;
            destinationLocked: boolean;
            enabled: boolean;
            filePolicy: components["schemas"]["FilePolicy"];
            /** @enum {string} */
            filePolicyMode: "global" | "override";
            id: string;
            inlineMultimodalEnabled: boolean;
            /** @enum {string} */
            inlineMultimodalMode: "global" | "override";
            itemCount: number;
            lastRun: components["schemas"]["runDTO"] | null;
            name: string;
            nextRunAt: string | null;
            observationScope: components["schemas"]["Scope"];
            /** @enum {string} */
            observationScopeMode: "global" | "override";
            policyRevision: number;
            reconcileRequired: boolean;
            retainStrategy: string;
            running: boolean;
            sourceConfig: {
                [key: string]: unknown;
            };
            sourceCredentialId: string;
            sourceFilter: components["schemas"]["Filter"];
            sourceType: string;
            state: components["schemas"]["taskStateDTO"];
            updatedAt: string;
        };
        taskStateDTO: {
            hasCursor: boolean;
            lastFullReconcileAt: string | null;
            lastStartedAt: string | null;
            lastSuccessAt: string | null;
        };
        testDTO: {
            message: string;
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_connectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["connectorsDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_credentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["credentialDTO"][];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_credentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    config: {
                        [key: string]: unknown;
                    };
                    customHeaders?: {
                        [key: string]: string;
                    };
                    name: string;
                    proxy?: components["schemas"]["credentialProxyBody"];
                    /** @enum {string} */
                    proxyMode?: "global" | "override";
                    type: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["credentialDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_credentials_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["credentialDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    delete_api_credentials_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    patch_api_credentials_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    config?: {
                        [key: string]: unknown;
                    };
                    customHeaders?: {
                        [key: string]: string;
                    };
                    name?: string;
                    proxy?: components["schemas"]["credentialProxyBody"];
                    /** @enum {string} */
                    proxyMode?: "global" | "override";
                    type?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["credentialDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_credentials_id_browse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    config?: {
                        [key: string]: unknown;
                    };
                    kind?: string;
                    parentId?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseResult"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_credentials_id_oauth_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["oauthStartDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_credentials_id_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["credentialDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_credentials_id_strategies: {
        parameters: {
            query: {
                bankId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["strategiesDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_credentials_id_tags: {
        parameters: {
            query: {
                bankId: string;
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPage"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_credentials_id_test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["testDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["dashboardDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["healthDTO"];
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_oauth_callback: {
        parameters: {
            query: {
                state: string;
                code?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Found */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_runs: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string;
                taskId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["runPageDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_runs_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["runDetailDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["settingsDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    patch_api_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    filePolicy?: components["schemas"]["FilePolicy"];
                    fullReconcileIntervalHours?: number;
                    incrementalSyncEnabled?: boolean;
                    inlineMultimodalEnabled?: boolean;
                    maxFileSizeMB?: number;
                    observationScope?: components["schemas"]["Scope"];
                    proxy?: components["schemas"]["Config"];
                    timezone?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["settingsDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["taskDTO"][];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cronExpression?: string;
                    customMetadata?: {
                        [key: string]: string;
                    };
                    customTags?: string[];
                    destinationBankId: string;
                    destinationCredentialId: string;
                    enabled?: boolean;
                    filePolicy?: components["schemas"]["FilePolicy"];
                    /** @enum {string} */
                    filePolicyMode?: "global" | "override";
                    inlineMultimodalEnabled?: boolean;
                    /** @enum {string} */
                    inlineMultimodalMode?: "global" | "override";
                    name: string;
                    observationScope?: components["schemas"]["Scope"];
                    /** @enum {string} */
                    observationScopeMode?: "global" | "override";
                    retainStrategy?: string;
                    sourceConfig?: {
                        [key: string]: unknown;
                    };
                    sourceCredentialId: string;
                    sourceFilter?: components["schemas"]["Filter"];
                    sourceType: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["taskDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_tasks_validate_cron: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cronExpression: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["cronDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_tasks_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["taskDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    delete_api_tasks_id: {
        parameters: {
            query?: {
                deleteDocuments?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    patch_api_tasks_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cronExpression?: string;
                    customMetadata?: {
                        [key: string]: string;
                    };
                    customTags?: string[];
                    destinationBankId?: string;
                    destinationCredentialId?: string;
                    enabled?: boolean;
                    filePolicy?: components["schemas"]["FilePolicy"];
                    /** @enum {string} */
                    filePolicyMode?: "global" | "override";
                    inlineMultimodalEnabled?: boolean;
                    /** @enum {string} */
                    inlineMultimodalMode?: "global" | "override";
                    name?: string;
                    observationScope?: components["schemas"]["Scope"];
                    /** @enum {string} */
                    observationScopeMode?: "global" | "override";
                    retainStrategy?: string;
                    sourceConfig?: {
                        [key: string]: unknown;
                    };
                    sourceCredentialId?: string;
                    sourceFilter?: components["schemas"]["Filter"];
                    sourceType?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["taskDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_tasks_id_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["cancelDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    delete_api_tasks_id_documents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["deleteDocumentsDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_tasks_id_dry_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_tasks_id_full_reconcile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["runTriggeredDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_tasks_id_full_reingest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["runTriggeredDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    post_api_tasks_id_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["runTriggeredDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
    get_api_tasks_id_runs: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string;
                taskId?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["runPageDTO"];
                };
            };
            /** @description Basic Auth required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description API error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apiError"];
                };
            };
        };
    };
}
