const COPY_KEYS: Record<string, string> = {
  "File System": "fileSystem",
  "Integration token": "integrationToken",
  "Data source": "dataSource",
  "Page title": "pageTitle",
  "Last edited": "lastEdited",
  Created: "created",
  "OAuth client ID": "oauthClientId",
  "OAuth client secret": "oauthClientSecret",
  Drive: "drive",
  Folder: "folder",
  "Include sub-folders": "includeSubfolders",
  "Export Google Docs/Sheets/Slides": "exportGoogleDocs",
  "File name": "fileName",
  Path: "path",
  Extension: "extension",
  "MIME type": "mimeType",
  "File type": "fileType",
  "Size (bytes)": "sizeBytes",
  Modified: "modified",
  "Root directory": "rootDirectory",
  "Root folder": "rootFolder",
  "Server URL": "serverUrl",
  Username: "username",
  "Password / app password": "passwordApp",
  "Bearer token": "bearerToken",
  Endpoint: "endpoint",
  Region: "region",
  "Access key ID": "accessKeyId",
  "Secret access key": "secretAccessKey",
  "Session token": "sessionToken",
  "Path-style addressing": "pathStyle",
  "Base URL": "baseUrl",
  "Instance ID": "instanceId",
  "API token": "apiToken",
  Notebook: "notebook",
  "Path prefix": "pathPrefix",
  Bucket: "bucket",
  Prefix: "prefix",
  "Application (client) ID": "applicationId",
  "Client secret": "clientSecret",
  Tenant: "tenant",
  Title: "title",
  Updated: "updated",
  Tags: "tags",
  "Plain text": "plainText",
  Documents: "documents",
  Images: "images",
  Audios: "audios",
  "Notion internal integration token with read access to shared data sources": "notionDescription",
  "SiYuan kernel API endpoint and token (Settings → About → API token)": "siYuanDescription",
  "Local files accessible to the application.": "filesystemDescription",
  "Google account via OAuth (read-only Drive access)": "googleDriveDescription",
  "Microsoft account / Microsoft 365 via OAuth (OneDrive and SharePoint)": "oneDriveDescription",
  "Amazon S3, MinIO, Cloudflare R2, Backblaze B2, Wasabi, …": "s3Description",
  "Nextcloud, ownCloud, Synology, Apache mod_dav, rclone serve, …": "webdavDescription",
  "Hindsight API endpoint used as a destination": "hindsightDescription",
  "Absolute path on the application server. In Docker, use the mounted container path.": "filesystemRootHelp",
  "Relative to the credential's root directory. Use . for the root.": "filesystemFolderHelp",
  "Notion data source ID (not the database ID). Use Browse to pick one shared with the integration.": "notionDataSourceHelp",
  "Stable identifier for this SiYuan instance. Leave empty to use its base URL.": "siYuanInstanceHelp",
  "Leave empty to use AWS S3.": "s3EndpointHelp",
  "Required by most self-hosted S3 servers (e.g. MinIO).": "s3PathStyleHelp",
  "Only objects under this key prefix.": "s3PrefixHelp",
  "Use instead of username/password if the server expects a token.": "webdavTokenHelp",
  "Path relative to the server URL.": "webdavRootHelp",
  "Leave empty for My Drive, or pick a shared drive.": "googleDriveHelp",
  "Leave empty for the whole drive.": "wholeDriveHelp",
  "Docs → Markdown, Sheets → CSV, Slides → PDF.": "googleExportHelp",
  "common, organizations, consumers, or a tenant ID.": "tenantHelp",
  "Leave empty for your personal OneDrive.": "oneDriveHelp",
  "Only documents whose human-readable path starts with this prefix.": "siYuanPathHelp",
  "Leave empty to sync every open notebook.": "siYuanNotebookHelp",
  "Sent as a Bearer token. Leave empty if the instance has no authentication.": "hindsightApiKeyHelp",
  "Use sync-collection (RFC 6578) when available": "syncCollectionHelp",
};

const EXISTING_KEYS: Record<string, string> = {
  plainText: "filePolicy.plainText",
  documents: "filePolicy.documents",
  images: "filePolicy.images",
  audios: "filePolicy.audios",
};

export function providerCopy(text: string | undefined, t: (key: string, options?: Record<string, unknown>) => string): string {
  if (!text) return "";
  const key = COPY_KEYS[text];
  if (!key) return text;
  const existing = EXISTING_KEYS[key];
  return existing ? t(existing) : t(`providerCopy.${key}`, { defaultValue: text });
}
